### PR TITLE
PHP 8 Support

### PR DESCRIPTION
**Pull request by brusch**

### CODE REVIEW

**Comment by Ryouzanpaku** [comment]
@brusch  there are further adjustments necessary, we are already planing an update to support PHP8.

**Comment by brusch** [comment]
@Ryouzanpaku thanks for your feedback,  do you have already a rough eta for that?

**Comment by ampaze** [comment]
@Ryouzanpaku May I ask what the hold up with PHP 8 is?

**Comment by ismetsener** [comment]
hi ,

when do you expect that
unzerdev / php-sdk     will work with PHP8 ?

with kind regarrds,
Ismet

**Pull request closed without merging**
